puts "there are #{100} cats."
puts "there are only #{30} dogs available."
puts "ther will be #{100 - 30} empty trashcan today."
puts "we can transport #{8 * 7} people today."
puts "we have #{90} to carpool today."
puts "we need to put about #{90 / 10} in each car."